### ISSUE TITLE
Add Team via Token

### ISSUE THREAD

**Issue by jonthegeek** [yonicd/slackteams#12]
As a shiny app, I'd like to add (and/or activate) a team using just a token, or maybe token + team name (although that's in the httr token, so, if we require that rather than just the string, the httr token will be enough).

This can be used by #11, but is also needed on its own (because the shiny app will handle the calls to generate the token).

**Comment by yonicd** [comment]
link to another issue https://github.com/yonicd/slackteams/issues/15
