### ISSUE TITLE
Check .slack populators

### ISSUE THREAD

**Issue by jonthegeek** [yonicd/slackteams#17]
I think there's still a legacy non-slackcalls call or two left in the thing that populates .slack$channels and/or .slack$users. I *think* this is currently much slower than it needs to be. Let's fix that.

It's possible I'm wrong, but I'm not able to confirm at the moment and wanted to log the thought.

**Comment by jonthegeek** [comment]
In `activate_team`, this call is super slow for R4DS: `slack_team_info(team)`.

I'm currently profiling, then will dig into whether we can fix this ~easily.

**Comment by yonicd** [comment]
I’ll dig into this too. Thanks for flagging this.

**Comment by yonicd** [comment]
The [API calls](https://github.com/yonicd/slackteams/blob/master/R/api.R) all look like they are using `slackcalls`. It could be the [tidy_slack](https://github.com/yonicd/slackteams/blob/master/R/tidy_slack.R) piece that is slowing things down.

**Comment by yonicd** [comment]
yeah. it is this is that is slowing things down. The api call returns fast the content but to tidy up the info takes a long timedue to size (38mb for r4ds) https://github.com/yonicd/slackteams/blob/a8f2edffe48a60712bf5190f25b2efa0df10d8cc/R/tidy_slack.R#L34

**Comment by yonicd** [comment]
There is an option to import [purrr](https://github.com/tidyverse/purrr/blob/master/DESCRIPTION). 

Pluses: It doesn't import the kitchen sink like other tidy packages. 
Minuses: We will be chasing our tail with every changing APIs that r-lib tend to go through.

**Comment by yonicd** [comment]
I made a branch with purrr instead of base mappers: https://github.com/yonicd/slackteams/tree/purrr

**Comment by yonicd** [comment]
Pr https://github.com/yonicd/slackteams/pull/18
