### ISSUE TITLE
Return token invisibly from add_team_code

### ISSUE THREAD

**Issue by jonthegeek** [yonicd/slackteams#21]
As a slackteams + shiny user, I'd like to get the actual token used during add_team_code, so that I can set a cookie with that token (to make future auth easier).

**Comment by yonicd** [comment]
you can access that on any active team.

```r
slackteams::get_team_env()
```

**Comment by jonthegeek** [comment]
`Sys.getenv("SLACK_API_TOKEN")` specifically. Closed the PR.
