### ISSUE TITLE
get_channel_info doesn't handle NA channel names

### ISSUE THREAD

**Issue by TylerGrantSmith** [yonicd/slackteams#24]
`slackteams::get_channel_info("wins_and_feedback")` errors on the R4DS slack.  It appears `get_team_channels` sometimes returns a channel with an `id` but no `name`.  This causes problems with the subsetting to determine `id` which then causes the `switch` to error.

In addition, could the function take a name xor an id?

**Comment by yonicd** [comment]
the master was updated today. reinstall and `slackteams::get_channel_info("wins_and_feedback")` should be fine.

as the switch which has been replaced and should be more stable.

**Comment by yonicd** [comment]
fixed https://github.com/yonicd/slackthreads/commit/85bf584d7bf8b7368d42ce6c6821539f43db4ddd
