### ISSUE TITLE
Specify channel types

### ISSUE THREAD

**Issue by jonthegeek** [yonicd/slackteams#27]
`get_team_channels` is the exported wrapper around the internal function `get_conversations_list`. `get_conversations_list` rightly has a "type" argument to restrict which types of channels we're getting, but the wrapper around `get_conversations_list` doesn't have that argument (and, in fact, calls `get_conversations_list` without arguments).

Looking at it more... I think that's probably right, for the case where we want to fully populate the team channels environment variable. But I think we should export `get_conversations_list` for advanced users who want to grab parts of the info (ie, for mentordash).

Gonna use `:::` to try it out and make sure I can do what I want, and then I'll probably PR.

**Comment by yonicd** [comment]
Makes sense. Waiting for PR

Couldn’t users just filter the output of get_team_channels?

**Comment by jonthegeek** [comment]
In theory, doing it in the request should make the process faster, particularly if they have a lot of private channels (for example). Don't make the API return a bunch of stuff that the user will immediately throw away.
