### ISSUE TITLE
Turn default path ~/slackr.json into a hidden file

### ISSUE THREAD

**Issue by jmbuhr** [yonicd/slackteams#4]
Currently, the default configuration file is ~/slackr.json. This goes against the common practice of most (unix) tools to prefix their configuration files with a dot (like .bashrc, .vimrc, .user_profile etc.) so that they are hidden by most file explorers by default. So I think it would be great if we could add that "." as well, to not clutter a users home folder.

**Comment by yonicd** [comment]
no problem. I’ll get to it later today. Thanks for the advice

**Comment by yonicd** [comment]
this should be a simple enough solution

```
library(slackteams)

load_teams()
The following teams are loaded:
  slackr, r4ds

load_teams(file = '~/slackr.json')
'slackr.json' is being deprecated
  Please rename 'slackr.json' to '.slackteams'


The following teams are loaded:
  slackr, r4ds
```

**Comment by yonicd** [comment]
you can test out the new default path on this branch. https://github.com/yonicd/slackteams/tree/new_file

**Comment by yonicd** [comment]
merged PR https://github.com/yonicd/slackteams/pull/5
