### ISSUE TITLE
Multiple Hits for Channels

### ISSUE THREAD

**Issue by jonthegeek** [yonicd/slackteams#7]
1. Create multiple private conversation channels on a slack team, each containing the same person (that person being you works fine).
2. Post a block to a channel, using your username (not the actual channel ID).

Expected result: The message posts to the you-only channel.
Actual result: The message posts to whichever unnamed DM channel you joined first, which may or may not be the you-only channel, and gives you a warning about multiple matches.

I think this comes from row 124 of `post.R`. You need to make the search more specific, probably by enclosing "channel" in "^" and "$". But... it seems like slackteams should be dealing with this entirely, so I'm not certain what that code block is supposed to be doing.

**Comment by yonicd** [comment]
this should fix the issue: https://github.com/yonicd/slackteams/commit/48611e601e4283cb4be0b6d388cfce21e2b9506a
